export const buttons = [
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: '',
    imgAlt: 'Stack Builder Button',
    text: 'Stack Builder',
    className: 'text-2xl font-bold bg-gradient-to-r from-amber-500 to-pink-500 w-full mb-4 hover:text-white',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
  {
    href: '/story/zenith-design-system-home-page-buttons--stack-builder',
    imgSrc: 'https://github.com/storybookjs/brand/raw/main/icon/icon-storybook-default.svg',
    imgAlt: 'Storybook Logo',
    text: 'Storybook',
    className: 'bg-violet-950',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
  {
    href: '/eslint-config-inspector/rules',
    imgSrc: 'https://eslint-config.antfu.me/favicon.svg',
    imgAlt: 'ESLint Logo',
    text: 'Style Guide',
    className: 'bg-gray-900',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg',
    imgAlt: 'GitHub Logo',
    text: 'GitHub',
    className: 'bg-green-600',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
  {
    href: '/docs',
    imgSrc: '/fumadocs_logo.svg',
    imgAlt: 'Fumadocs Logo',
    text: 'Docs',
    className: 'bg-slate-600',
    target: '_blank',
    rel: 'noreferrer noopener',
  },
]
