export const buttons = [
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: '/stack-builder-home-screenshot.png',
    imgAlt: 'Stack Builder Homepage screenshot',
    logoSrc: '/logos/stack_builder.svg',
    text: 'Stack Builder',
    className: 'text-2xl text-black bg-custom-gradient-ltr w-full mb-4 hover:bg-custom-gradient-rtl',
  },
  {
    href: 'https://www.figma.com/design/XILd6bWRSYGnvpHzPWqqkE/Zenith-Design-System?node-id=6-48&t=helPlLiU9UcstWzx-1',
    imgSrc: '/stack-builder-figma-screenshot.png',
    imgAlt: 'Stack Builder Figma screenshot',
    logoSrc: '/logos/figma.svg',
    text: 'Figma',
    className: 'bg-indigo-500 hover:bg-indigo-400',
  },
  {
    // href: '/story/zenith-design-system-home-page-buttons--stack-builder',
    href: 'https://66940475e3e13dde7d47c07f-ssiehonydf.chromatic.com/?path=/story/zenith-design-system-home-page-buttons--stack-builder',
    imgSrc: '/stack-builder-storybook-screenshot.png',
    imgAlt: 'Stack Builder Storybook screenshot',
    logoSrc: '/logos/storybook.svg',
    text: 'Storybook',
    className: 'bg-violet-950 hover:bg-purple-800',
  },
  {
    href: '/eslint-config-inspector/rules',
    imgSrc: '/stack-builder-eslint-config-inspector-screenshot.png',
    imgAlt: 'Stack Builder ESLint screenshot',
    logoSrc: '/logos/anthony_fu_eslint.svg',
    text: 'Style Guide',
    className: 'bg-indigo-950 hover:bg-indigo-900',
  },
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: '/stack-builder-github-screenshot.png',
    imgAlt: 'Stack Builder GitHub screenshot',
    logoSrc: '/logos/github.svg',
    text: 'GitHub',
    className: 'bg-green-600 hover:bg-green-400',
  },
  {
    href: '/docs',
    imgSrc: '/stack-builder-docs-screenshot.png',
    imgAlt: 'Stack Builder Fumadocs screenshot',
    logoSrc: '/logos/fumadocs.svg',
    text: 'Docs',
    className: 'bg-slate-600 hover:bg-slate-400',
  },
]
