export const buttons = [
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: '/stack-builder-home-screenshot.png',
    imgAlt: 'Stack Builder Homepage screenshot',
    logoSrc: '/logos/stack_builder.svg',
    text: 'Stack Builder',
    className: 'text-2xl text-black bg-custom-gradient-ltr w-full mb-4 hover:bg-custom-gradient-rtl',
  },
  {
    href: '/story/zenith-design-system-home-page-buttons--stack-builder',
    imgSrc: '/stack-builder-storybook-screenshot.png',
    imgAlt: 'Stack Builder Storybook screenshot',
    logoSrc: 'https://github.com/storybookjs/brand/raw/main/icon/icon-storybook-default.svg',
    text: 'Storybook',
    className: 'bg-violet-950 hover:bg-purple-800',
  },
  {
    href: '/eslint-config-inspector/rules',
    imgSrc: '/stack-builder-eslint-config-inspector-screenshot.png',
    imgAlt: 'Stack Builder ESLint screenshot',
    logoSrc: 'https://eslint-config.antfu.me/favicon.svg',
    text: 'Style Guide',
    className: 'bg-indigo-950 hover:bg-indigo-900',
  },
  {
    href: 'https://github.com/MFarabi619/stack-builder',
    imgSrc: '/stack-builder-github-screenshot.png',
    imgAlt: 'Stack Builder GitHub screenshot',
    logoSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg',
    text: 'GitHub',
    className: 'bg-green-600 hover:bg-green-400',
  },
  {
    href: '/docs',
    // imgSrc: '/fumadocs_logo.svg',
    imgSrc: '/stack-builder-docs-screenshot.png',
    imgAlt: 'Stack Builder Fumadocs screenshot',
    logoSrc: 'https://svgshare.com/i/189M.svg',
    text: 'Docs',
    className: 'bg-slate-600 hover:bg-slate-400',
  },
]
